### ISSUE TITLE
/scripts/gcc-ld is causing troubles with --parm name=value type of compiler flags

### ISSUE THREAD

**Issue by ytrezq** [andikleen/linux-misc#14]
When using setting`--param`internals,`/scripts/gcc-ld`trigger some kind of split in the FLAGS, so`name=value`in`--param name=value`are interpreted as file names.

`gcc-4.9`
`lto-3.16` branch

Those type of options were handled by`/scripts/gcc-ld`up to the`lto-3.14`branch.
I wasn’t able to find why you removed it.

**Comment by andikleen** [comment]
I tested it and it works for me.

+LTO_CFLAGS += --param max-inline-insns-auto=10000

How did you specify the param?

**Comment by andikleen** [comment]
Never mind, of course it needed to be LTO_FINAL_CFLAGS.

Fixed now in lto-4.0
