### ISSUE TITLE
Packaging for Arch AUR - version string?

### ISSUE THREAD

**Issue by staalmannen** [andikleen/linux-misc#15]
Hi
I have packaged binutils-hjl-git and kernel-lto on the AUR:
https://aur.archlinux.org/packages/binutils-hjl-git/

https://aur.archlinux.org/pkgbase/linux-lto-git/
(I do rather extreme default CFLAGS with -march=native and -Ofast
Do I need to add LDFLAGS? Some info about lto on line suggests that it is needed)

One thing that is rather weird is that even if I use the lto-4.0 branch, the version string I see when I run "git describe" is: v2.6.35-305914-g6842019
What could be wrong?

If I look at the commits with git log -p -1, I get a commit from 19th of April so it is not that I accidentally pull the wrong branch (I think).

PS. If someone got suggestions / ideas for improvements of my packages - please let me know :)
DS.

**Comment by andikleen** [comment]
I guess my git directory is missing the tags. You can fetch them yourself from another kernel repository. I'll upload them later today.

**Comment by andikleen** [comment]
Pushed the tags now
