### ISSUE TITLE
[4.11] CONFIG_LTO & CONFIG_PARAVIRT_SPINLOCKS doesn't work

### ISSUE THREAD

**Issue by gschukin** [andikleen/linux-misc#19]
If I enable CONFIG_PARAVIRT_SPINLOCKS option build fais with:
```
./ccUmpSBT.ltrans0.ltrans.o: In function `optprobe_template_end':
<artificial>:(.text+0xb3): undefined reference to `steal_time'
collect2: error: ld returned 1 exit status
```

**Comment by andikleen** [comment]
Thanks for testing.
Had already fixed, but forgot to push. Done now.

BTW if you have any recent performance numbers with LTO please send them.

**Comment by gschukin** [comment]
Currently there is no difference between lto and non-lto kernel.

Once 4.11 kernel and gcc 7 will be available I'll run additional benchmarks.

If you would like some particular benchmarks or configuration, let me know and I'll include them also.
