### ISSUE TITLE
LTO kernels fail to build with many "... relocation R_X86_64_32S against ..." linking errors

### ISSUE THREAD

**Issue by telans** [andikleen/linux-misc#32]
```
/usr/bin/ld: ./.tmp_vmlinux.kallsyms1.KgBLDA.ltrans0.ltrans.o: relocation R_X86_64_32S against hidden symbol `cpu_hw_events' can not be used when making a PIE object
/usr/bin/ld: ./.tmp_vmlinux.kallsyms1.KgBLDA.ltrans1.ltrans.o: relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ./.tmp_vmlinux.kallsyms1.KgBLDA.ltrans2.ltrans.o: relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ./.tmp_vmlinux.kallsyms1.KgBLDA.ltrans3.ltrans.o: relocation R_X86_64_32S against symbol `em_bsf' can not be used when making a PIE object; recompile with -fPIE
```

Some people have had success building, however, myself and at least one other person have been getting these errors. See https://github.com/InBetweenNames/gentooLTO/issues/90#issuecomment-671143495

LD is set to ld.bfd, this occurs regardless of the -O level used or -march options. 

Cheers

---

Turns out it's due to GCC/toolchain being built with PIE. `make KCFLAGS="-fno-pie -fno-PIE -Wl,-no-pie" LDFLAGS_MODULE="Wl,-no-pie"` doesn't change anything.

**Comment by mssx86** [comment]
i'm the guy in that quoted comment, will try rebuilding gcc and binutils w/o pie and report back if that fixes anything.

**Comment by ijinma** [comment]
@mssx86 
hi, I have just started to learn the kernel. I am very interested in the LTO kernel, and have tested the clang [LTO kernel ](https://github.com/samitolvanen/linux/tree/tip/clang-lto)of Sami. The [results](https://github.com/samitolvanen/linux/commit/39c19542a337a34455cc81c63a49d7d039d58635#commitcomment-44890247) show that there is almost no benefit, especially in terms of volume. 

So I turned to Andi's GCC LTO kernel test, but after several weeks I still [failed](https://github.com/andikleen/linux-misc/issues/34) to run successfully, which was very painful for me. The compiler and the LTO kernel have tried different versions. The compiled systems include Ubuntu 16, Ubuntu 18 and CentOS, and the platforms include virtual machines and physical machines. Unfortunately, I have not succeeded. 

Can you tell me the specific environment in which you run successfully? It would be perfect to provide a compilation process.

Thanks,
jinma
