### ISSUE TITLE
How to compile kernel with GCC LTO in ARM?

### ISSUE THREAD

**Issue by jinm0914** [andikleen/linux-misc#33]
I am a beginner. I am very interested in the LTO kernel at present and want to use LTO to compile the kernel on ARM. 

In [kernel-lto.pdf](http://halobates.de/kernel-lto.pdf), I see "tested on X86, arm, MIPs" and "branch lto-3. X", but I see "only tested on X86 for now." in branch lto-3. X. It seems that ARM is not supported. I also tried branch lto-4. X and branch lto-5. X, but failed. 

In [Microsoft-Exploring-PGO-Linux](https://www.phoronix.com/scan.php?page=news_item&px=Microsoft-Exploring-PGO-Linux), I see that Microsoft seems to have succeeded, but I haven't found the relevant kernel code or relevant documents. 

How can I compile the kernel successfully with LTO in ARM? thank you!

**Comment by jinm0914** [comment]
@andikleen Could you give me some advice？Thank you.

**Comment by arndb** [comment]
See Sami's recent work at https://lore.kernel.org/lkml/20201118220731.925424-1-samitolvanen@google.com/
